### ISSUE TITLE
interaction.deferReply() cannot use with modal

### ISSUE THREAD

**Issue by 3raphat** [kaogeek/kaogeek-discord-bot#100]
https://github.com/creatorsgarten/kaogeek-discord-bot/blob/975d08b08b95f7a089ff3ea4a67988954d3f44f0/src/events/interactionCreate.ts#L15-L17

![image](https://github.com/creatorsgarten/kaogeek-discord-bot/assets/96657413/ff733fc4-76fa-41c2-b863-fde6afbd11a7)

refs:
https://discordjs.guide/interactions/modals.html#building-and-responding-with-modals
https://stackoverflow.com/questions/74444213/discord-js-interaction-already-replied-error-while-sending-modal

**Comment by Leomotors** [comment]
My opinion is we should only deferReply only for command that needs to.
We should remove deferReply in this file and require each command to defer explicitly instead.
