### ISSUE TITLE
[FEATURE] Sticky Message in chat

### ISSUE THREAD

**Issue by LagSeeN** [kaogeek/kaogeek-discord-bot#102]
### Overview

1. when set message for sticky in chanel
2. someone send message in chanel >> sticky message will delete and send sticky messages to the bottom always.

### Why you want this feature?

1. Free StickyBot Free Version can set 3 message

**Comment by dtinth** [comment]
@LagSeeN sounds like a great suggestion.

maybe we can use a similar command, but use `?sticky` instead of `?stick` to avoid conflict with the normal StickyBot.

if someone wants to implement it, please comment so everyone knows someone is working on it.

**Comment by samithiwat** [comment]
I can krub, please assign this ticket to me

**Comment by quarkhadron** [comment]
Assigned to @samithiwat krub 🙏
